### ISSUE TITLE
stealer?

### ISSUE THREAD

**Issue by dyrkuwu** [Sydiepus/Skynode-server-renewer#1]

**Comment by Sydiepus** [comment]
No?

**Comment by Sydiepus** [comment]
@KoteToste Can you please reference the repo that you suspect me stealing from it?

**Comment by Sydiepus** [comment]
maybe i jumped to a conclusion that's not right sorry for that.
if you're asking if this is an account stealer no it is not.
i think it's very clear in the source code that's why it's open source (to check before running since it's a simple script).

**Comment by dyrkuwu** [comment]
ok

чт, 9 дек. 2021 г., 11:44 None Noen ***@***.***>:
